import { defineConfig } from '@playwright/test';
import path from 'path';

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:3210';
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3100';

/**
 * Persistent auth session files — one per role.
 * Generated by tests/smoke/auth.setup.ts and consumed by all spec projects.
 */
export const SESSION_DIR = path.join(__dirname, '.playwright', 'sessions');
export const SESSIONS = {
  super_admin: path.join(SESSION_DIR, 'super-admin.json'),
  ops_manager: path.join(SESSION_DIR, 'ops-manager.json'),
  ops_technician: path.join(SESSION_DIR, 'ops-technician.json'),
  customer_admin: path.join(SESSION_DIR, 'customer-admin.json'),
  customer_orderer: path.join(SESSION_DIR, 'customer-orderer.json'),
  customer_viewer: path.join(SESSION_DIR, 'customer-viewer.json'),
} as const;

export { API_URL, BASE_URL };

export default defineConfig({
  testDir: './tests',
  outputDir: '.playwright/results',

  // Runs once before all tests/projects. Fails fast with a clear message if
  // the NestJS API is not running or the database is not seeded.
  globalSetup: './tests/global-setup.ts',

  // Auto-start the Next.js dev server if it is not already listening.
  // `reuseExistingServer: true` means: if something is already answering on
  // BASE_URL (e.g. you ran `pnpm dev` in another terminal, or the server was
  // already started in CI), Playwright reuses it and skips the command.
  // If the port is free, Playwright runs `pnpm dev` and waits up to 2 min.
  //
  // ⚠️  The NestJS API must be started separately — it needs DATABASE_URL and
  // other env vars from your .env file which may not be available here.
  // Run it from the repo root: `pnpm --filter @xc/api dev`
  webServer: {
    command: 'pnpm dev',
    url: BASE_URL,
    reuseExistingServer: true,
    timeout: 120_000,
    stdout: 'pipe',
    stderr: 'pipe',
  },

  // Never run tests in parallel — shared DB state and auth cookies make
  // parallel execution unreliable without per-worker isolation.
  fullyParallel: false,
  workers: 1,

  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,

  reporter: [['html', { outputFolder: '.playwright/report', open: 'never' }], ['list']],

  use: {
    baseURL: BASE_URL,
    // Save a screenshot next to every failed test.
    screenshot: 'only-on-failure',
    video: 'off',
    // Capture a trace on the first retry so failures can be replayed.
    trace: 'on-first-retry',
    // Give slow CI environments enough time to load pages.
    navigationTimeout: 20_000,
    actionTimeout: 10_000,
  },

  projects: [
    // ── 1. Auth setup — logs in as every role and saves storage state ─────────
    {
      name: 'auth-setup',
      testMatch: /auth\.setup\.ts/,
    },

    // ── 2. Operator smoke tests ───────────────────────────────────────────────
    {
      // super-admin also runs route-protection: the spec pins its own
      // storageState per describe block via test.use(), so all roles are
      // covered in a single project pass.
      name: 'super-admin',
      use: { storageState: SESSIONS.super_admin },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-operator\.spec\.ts/, /route-protection\.spec\.ts/],
    },
    {
      name: 'ops-manager',
      use: { storageState: SESSIONS.ops_manager },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-operator\.spec\.ts/],
    },
    {
      name: 'ops-technician',
      use: { storageState: SESSIONS.ops_technician },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-operator\.spec\.ts/],
    },

    // ── 3. Customer smoke tests ───────────────────────────────────────────────
    {
      name: 'customer-admin',
      use: { storageState: SESSIONS.customer_admin },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-customer\.spec\.ts/],
    },
    {
      name: 'customer-orderer',
      use: { storageState: SESSIONS.customer_orderer },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-customer\.spec\.ts/],
    },
    {
      name: 'customer-viewer',
      use: { storageState: SESSIONS.customer_viewer },
      dependencies: ['auth-setup'],
      testMatch: [/crawl-customer\.spec\.ts/],
    },
  ],
});
