// ══════════════════════════════════════════════════════════════════════════════
// CROSS-CONNECT ORDER LIFECYCLE
//
// Purpose:
//   Governs the commercial request from initial draft through approval or
//   rejection. The order is the immutable record of customer intent; it does
//   not track ongoing service health (that is CrossConnectService).
//
// State diagram:
//
//   draft ──────────────────────────────────────────────────────► cancelled
//     │                                                               ▲
//     ▼                                                               │
//   submitted ────────────────────────────────────────────────────► cancelled
//     │                                                               ▲
//     ▼                                                               │
//   under_review ─────────────────────────────────────────────────► cancelled
//     │                                           │                   ▲
//     ▼                                           ▼                   │
//   pending_approval ──────────────────────────► rejected         cancelled
//     │
//     ▼
//   approved  (terminal — service record is created as side effect)
//
// Billing: no billing events generated by order state changes.
//         BillingTriggerEvent is only emitted when the SERVICE activates.
// ══════════════════════════════════════════════════════════════════════════════

import { OrderState, UserRole } from '@xc/types';
import {
  InsufficientRoleError,
  MissingTransitionDataError,
  TransitionGuardError,
} from '../../common/errors/domain.errors';
import { TransitionContext, TransitionDef } from '../../common/state-machine/state-machine';

// The minimal shape that the guard functions need to inspect.
export interface OrderGuardEntity {
  id: string;
  state: OrderState;
  submittedById: string;
  requestingOrgId: string;
  // Endpoints from a joined query (two expected: a_side + z_side)
  endpoints: Array<{ side: string; loaNumber?: string | null; endpointType: string }>;
}

type OrderCtx = TransitionContext<OrderGuardEntity>;

// ── Guard helpers ─────────────────────────────────────────────────────────────

function requireRole(ctx: OrderCtx, ...roles: UserRole[]): void {
  if (!ctx.actorRole || !(roles as string[]).includes(ctx.actorRole)) {
    throw new InsufficientRoleError(roles, ctx.actorRole);
  }
}

function requireField(ctx: OrderCtx, field: string): void {
  const value = ctx.payload?.[field];
  if (!value || (typeof value === 'string' && value.trim() === '')) {
    throw new MissingTransitionDataError(field);
  }
}

function requireBothEndpoints(ctx: OrderCtx): void {
  const sides = ctx.entity.endpoints.map((e) => e.side);
  if (!sides.includes('a_side') || !sides.includes('z_side')) {
    throw new TransitionGuardError(
      'Both a_side and z_side endpoints must be defined before submitting',
    );
  }
}

function requireLoaForCarrierEndpoints(ctx: OrderCtx): void {
  for (const ep of ctx.entity.endpoints) {
    if (ep.endpointType === 'carrier' && !ep.loaNumber) {
      throw new TransitionGuardError(`LOA number is required for carrier endpoint on ${ep.side}`);
    }
  }
}

// ── Transition definitions ────────────────────────────────────────────────────

export const ORDER_TRANSITIONS: TransitionDef<OrderState, OrderGuardEntity>[] = [
  //
  // 1. draft → submitted
  //    Actor:  customer_admin
  //    Guards: both endpoints defined; LOA present for any carrier endpoint
  //
  {
    from: 'draft',
    to: 'submitted',
    description: 'Customer submits order for review',
    guard(ctx) {
      requireRole(ctx, UserRole.customer_admin, UserRole.customer_orderer, UserRole.super_admin);
      requireBothEndpoints(ctx);
      requireLoaForCarrierEndpoints(ctx);
    },
  },

  //
  // 2. submitted → under_review
  //    Actor:  system (auto on intake) or ops_technician / ops_manager
  //    Guards: none beyond role — intake job runs automatically
  //
  {
    from: 'submitted',
    to: 'under_review',
    description: 'Ops begins feasibility/capacity review',
    guard(ctx) {
      if (ctx.actorId) {
        // Only block if an actor is explicitly identified AND they have the wrong role
        requireRole(ctx, UserRole.ops_technician, UserRole.ops_manager, UserRole.super_admin);
      }
      // actorId = undefined means system/job — always allowed
    },
  },

  //
  // 3. under_review → pending_approval
  //    Actor:  ops_technician, ops_manager
  //    Guards: ops confirms capacity and LOA validity
  //    Side effects: creates ApprovalRequest record
  //
  {
    from: 'under_review',
    to: 'pending_approval',
    description: 'Feasibility confirmed — sent to manager for approval',
    guard(ctx) {
      requireRole(ctx, UserRole.ops_technician, UserRole.ops_manager, UserRole.super_admin);
    },
  },

  //
  // 4. under_review → rejected
  //    Actor:  ops_technician, ops_manager
  //    Guards: rejection reason required (infeasible: no capacity, bad LOA, etc.)
  //
  {
    from: 'under_review',
    to: 'rejected',
    description: 'Ops rejects as infeasible during review',
    guard(ctx) {
      requireRole(ctx, UserRole.ops_technician, UserRole.ops_manager, UserRole.super_admin);
      requireField(ctx, 'rejectionReason');
    },
  },

  //
  // 5. pending_approval → approved
  //    Actor:  ops_manager, super_admin
  //    Guards: approver must not be the same person who submitted the order
  //    Side effects: creates CrossConnectService, creates install WorkOrder,
  //                  sends customer notification
  //
  {
    from: 'pending_approval',
    to: 'approved',
    description: 'Manager approves the cross-connect order',
    guard(ctx) {
      requireRole(ctx, UserRole.ops_manager, UserRole.super_admin);
      if (ctx.actorId && ctx.actorId === ctx.entity.submittedById) {
        throw new TransitionGuardError(
          'The approver cannot be the same user who submitted the order',
        );
      }
    },
  },

  //
  // 6. pending_approval → rejected
  //    Actor:  ops_manager, super_admin
  //    Guards: rejection reason required
  //    Side effects: sends customer notification
  //
  {
    from: 'pending_approval',
    to: 'rejected',
    description: 'Manager rejects the order',
    guard(ctx) {
      requireRole(ctx, UserRole.ops_manager, UserRole.super_admin);
      requireField(ctx, 'rejectionReason');
    },
  },

  //
  // 7. [draft | submitted | under_review | pending_approval] → cancelled
  //    Actor:  customer_admin can cancel their own draft/submitted
  //            ops_manager/super_admin can cancel any non-terminal order
  //    Guards: for approved orders use service disconnect flow instead
  //    Note:   'approved' is intentionally excluded from the `from` list here;
  //            cancelling an approved order requires the service disconnect path
  //
  {
    from: ['draft', 'submitted', 'under_review', 'pending_approval'],
    to: 'cancelled',
    description: 'Order cancelled before approval',
    guard(ctx) {
      const requiredRoles: UserRole[] = [
        UserRole.customer_admin,
        UserRole.customer_orderer,
        UserRole.ops_manager,
        UserRole.super_admin,
      ];
      requireRole(ctx, ...requiredRoles);

      // Customers can only cancel orders belonging to their own org; ops can cancel anything.
      // Org-level check is done in the service layer, not here, to keep guards thin.
    },
  },
];

// ── Invalid transitions (documentation) ──────────────────────────────────────
//
//  approved     → any         BLOCKED — terminal; use service disconnect workflow
//  rejected     → any         BLOCKED — terminal
//  cancelled    → any         BLOCKED — terminal
//  pending_approval → submitted  BLOCKED — no backward traversal
//  any          → draft       BLOCKED — draft is an entry state only
//
// ─────────────────────────────────────────────────────────────────────────────

// ── Billing trigger implications ──────────────────────────────────────────────
//
//  None. Order state changes do not trigger billing events.
//  BillingTriggerEvent(service_activated) is emitted when CrossConnectService
//  transitions provisioning → active (triggered by WO completion, not order approval).
//
// ─────────────────────────────────────────────────────────────────────────────
