/**
 * tests/helpers/auth.ts
 *
 * Convenience re-exports and typed credential constants.
 * Use `loginAs` when you need to log in programmatically inside a test
 * (e.g. for refresh-token tests).  For all smoke/crawl tests, prefer the
 * session files generated by auth.setup.ts instead.
 */
import type { Page } from '@playwright/test';

export type RoleKey =
  | 'super_admin'
  | 'ops_manager'
  | 'ops_technician'
  | 'customer_admin'
  | 'customer_orderer'
  | 'customer_viewer';

export interface Credential {
  email: string;
  password: string;
  role: RoleKey;
  /** Where the middleware sends this role after login */
  homePath: string;
}

export const CREDENTIALS: Record<RoleKey, Credential> = {
  super_admin: {
    email: 'admin@crossconnect.local',
    password: 'changeme123!',
    role: 'super_admin',
    homePath: '/dashboard',
  },
  ops_manager: {
    email: 'ops@crossconnect.local',
    password: 'changeme123!',
    role: 'ops_manager',
    homePath: '/dashboard',
  },
  ops_technician: {
    email: 'tech@crossconnect.local',
    password: 'changeme123!',
    role: 'ops_technician',
    homePath: '/dashboard',
  },
  customer_admin: {
    email: 'alice@acme.example.com',
    password: 'changeme123!',
    role: 'customer_admin',
    homePath: '/portal',
  },
  customer_orderer: {
    email: 'bob@acme.example.com',
    password: 'changeme123!',
    role: 'customer_orderer',
    homePath: '/portal',
  },
  customer_viewer: {
    email: 'dave@acme.example.com',
    password: 'changeme123!',
    role: 'customer_viewer',
    homePath: '/portal',
  },
};

/**
 * Perform a full form-based login for the given role and wait for the
 * middleware redirect to complete.
 */
export async function loginAs(page: Page, role: RoleKey): Promise<void> {
  const cred = CREDENTIALS[role];
  await page.goto('/login');
  await page.fill('input[name="email"]', cred.email);
  await page.fill('input[name="password"]', cred.password);
  await page.click('button[type="submit"]');
  await page.waitForURL((url) => url.pathname.startsWith(cred.homePath), {
    timeout: 20_000,
  });
}
